var annotated_dup =
[
    [ "etcpal", null, [
      [ "Error", "classetcpal_1_1_error.html", "classetcpal_1_1_error" ],
      [ "BadExpectedAccess", "classetcpal_1_1_bad_expected_access.html", "classetcpal_1_1_bad_expected_access" ],
      [ "Expected", "classetcpal_1_1_expected.html", "classetcpal_1_1_expected" ],
      [ "EventGroup", "classetcpal_1_1_event_group.html", "classetcpal_1_1_event_group" ],
      [ "IpAddr", "classetcpal_1_1_ip_addr.html", "classetcpal_1_1_ip_addr" ],
      [ "SockAddr", "classetcpal_1_1_sock_addr.html", "classetcpal_1_1_sock_addr" ],
      [ "MacAddr", "classetcpal_1_1_mac_addr.html", "classetcpal_1_1_mac_addr" ],
      [ "LogTimestamp", "classetcpal_1_1_log_timestamp.html", "classetcpal_1_1_log_timestamp" ],
      [ "LogMessageHandler", "classetcpal_1_1_log_message_handler.html", "classetcpal_1_1_log_message_handler" ],
      [ "Logger", "classetcpal_1_1_logger.html", "classetcpal_1_1_logger" ],
      [ "Mutex", "classetcpal_1_1_mutex.html", "classetcpal_1_1_mutex" ],
      [ "MutexGuard", "classetcpal_1_1_mutex_guard.html", "classetcpal_1_1_mutex_guard" ],
      [ "OpaqueId", "classetcpal_1_1_opaque_id.html", "classetcpal_1_1_opaque_id" ],
      [ "Queue", "classetcpal_1_1_queue.html", "classetcpal_1_1_queue" ],
      [ "RecursiveMutex", "classetcpal_1_1_recursive_mutex.html", "classetcpal_1_1_recursive_mutex" ],
      [ "RecursiveMutexGuard", "classetcpal_1_1_recursive_mutex_guard.html", "classetcpal_1_1_recursive_mutex_guard" ],
      [ "RwLock", "classetcpal_1_1_rw_lock.html", "classetcpal_1_1_rw_lock" ],
      [ "ReadGuard", "classetcpal_1_1_read_guard.html", "classetcpal_1_1_read_guard" ],
      [ "WriteGuard", "classetcpal_1_1_write_guard.html", "classetcpal_1_1_write_guard" ],
      [ "Semaphore", "classetcpal_1_1_semaphore.html", "classetcpal_1_1_semaphore" ],
      [ "Signal", "classetcpal_1_1_signal.html", "classetcpal_1_1_signal" ],
      [ "Thread", "classetcpal_1_1_thread.html", "classetcpal_1_1_thread" ],
      [ "TimePoint", "classetcpal_1_1_time_point.html", "classetcpal_1_1_time_point" ],
      [ "Timer", "classetcpal_1_1_timer.html", "classetcpal_1_1_timer" ],
      [ "Uuid", "classetcpal_1_1_uuid.html", "classetcpal_1_1_uuid" ]
    ] ],
    [ "AcnPdu", "struct_acn_pdu.html", "struct_acn_pdu" ],
    [ "AcnPduConstraints", "struct_acn_pdu_constraints.html", "struct_acn_pdu_constraints" ],
    [ "AcnRootLayerPdu", "struct_acn_root_layer_pdu.html", "struct_acn_root_layer_pdu" ],
    [ "AcnTcpPreamble", "struct_acn_tcp_preamble.html", "struct_acn_tcp_preamble" ],
    [ "AcnUdpPreamble", "struct_acn_udp_preamble.html", "struct_acn_udp_preamble" ],
    [ "EtcPalAddrinfo", "struct_etc_pal_addrinfo.html", "struct_etc_pal_addrinfo" ],
    [ "EtcPalGroupReq", "struct_etc_pal_group_req.html", "struct_etc_pal_group_req" ],
    [ "EtcPalIpAddr", "struct_etc_pal_ip_addr.html", "struct_etc_pal_ip_addr" ],
    [ "EtcPalLinger", "struct_etc_pal_linger.html", "struct_etc_pal_linger" ],
    [ "EtcPalLogParams", "struct_etc_pal_log_params.html", "struct_etc_pal_log_params" ],
    [ "EtcPalLogStrings", "struct_etc_pal_log_strings.html", "struct_etc_pal_log_strings" ],
    [ "EtcPalLogTimestamp", "struct_etc_pal_log_timestamp.html", "struct_etc_pal_log_timestamp" ],
    [ "EtcPalMacAddr", "struct_etc_pal_mac_addr.html", "struct_etc_pal_mac_addr" ],
    [ "EtcPalMcastNetintId", "struct_etc_pal_mcast_netint_id.html", "struct_etc_pal_mcast_netint_id" ],
    [ "EtcPalMreq", "struct_etc_pal_mreq.html", "struct_etc_pal_mreq" ],
    [ "EtcPalNetintInfo", "struct_etc_pal_netint_info.html", "struct_etc_pal_netint_info" ],
    [ "EtcPalPollEvent", "struct_etc_pal_poll_event.html", "struct_etc_pal_poll_event" ],
    [ "EtcPalRbIter", "struct_etc_pal_rb_iter.html", "struct_etc_pal_rb_iter" ],
    [ "EtcPalRbNode", "struct_etc_pal_rb_node.html", "struct_etc_pal_rb_node" ],
    [ "EtcPalRbTree", "struct_etc_pal_rb_tree.html", "struct_etc_pal_rb_tree" ],
    [ "EtcPalSockAddr", "struct_etc_pal_sock_addr.html", "struct_etc_pal_sock_addr" ],
    [ "EtcPalSyslogParams", "struct_etc_pal_syslog_params.html", "struct_etc_pal_syslog_params" ],
    [ "EtcPalThreadParams", "struct_etc_pal_thread_params.html", "struct_etc_pal_thread_params" ],
    [ "EtcPalTimer", "struct_etc_pal_timer.html", "struct_etc_pal_timer" ],
    [ "EtcPalUuid", "struct_etc_pal_uuid.html", "struct_etc_pal_uuid" ],
    [ "IntHandleManager", "struct_int_handle_manager.html", "struct_int_handle_manager" ]
];