name: Notify PR about Staging Docs
on:
  pull_request:
    types: [opened]
jobs:
  comment:
    name: Comment on PR about Staging Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: comment_template.md
